name: Financial System CI Workflow

on:
  - push
  - pull_request

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch source code including submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lcov

      - name: Configure and build the system
        run: |
          cd banking
          mkdir -p build
          cd build
          cmake .. -DBUILD_UNIT_TESTS=ON -DENABLE_TEST_COVERAGE=ON
          make

      - name: Run unit validation suite
        run: |
          cd banking/build
          ctest --output-on-failure

      - name: Generate coverage metrics
        run: |
          cd banking/build
          lcov --ignore-errors mismatch --ignore-errors gcov --capture --directory . -o coverage.info || lcov --ignore-errors gcov --capture --directory . -o coverage.info
          lcov --extract coverage.info \
            "*/banking/Account.cpp" \
            "*/banking/Account.h" \
            "*/banking/Transaction.cpp" \
            "*/banking/Transaction.h" \
            -o filtered_coverage.info

      - name: Submit to coverage reporting service
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: banking/build/filtered_coverage.info
